### PR TITLE
Configurable minimum selector timeout

### PR DESCRIPTION
**Pull request by vmarian2**
Add a system property to configure the minimum selector timeout

### CODE REVIEW

**Review by ibauersachs — CHANGES_REQUESTED** [review]
Thanks for taking the time to address this.

- The `Options` class is somewhat legacy, I don't want to add more stuff there. Please use the property name `dnsjava.nio.selector_timeout` via `Integer.getInteger`.
- If the configured value is out of range (i.e. <= 0, larger than 1000), throw an exception.
- Document the new system property in the class' Javadoc and in the readme.
- Add a test if it's feasible, e.g. in NioTcpClientTest

If you want a release with this relatively soon, please target the branch `release/3.5.x` instead of master.

**Comment by vmarian2** [comment]
I am unsure what exception to use in this case. Got any suggestions?

**Comment by ibauersachs** [comment]
Please use IllegalArgumentException

**Comment by vmarian2** [comment]
Closed in favour of https://github.com/dnsjava/dnsjava/pull/282 which is branched from release/3.5.x.

**Pull request closed without merging**
