### PR TITLE
Adds japicmp plugin to ensure compatibility

### PR DESCRIPTION
**Pull request by kingle**
Per comment in https://github.com/dnsjava/dnsjava/issues/1#issuecomment-493774420
> when I see how much impact the other API changes will have. E.g. adding generics will not necessarily break APIs.

+1 on ensuring APIs don't break.  With this plugin, the build will fail when it detects incompatible API changes, compared to the previous version.  Also gives some insight/sanity checks on non-breaking changes (adding to API, removing method identical to superclass' implementation, etc.).

### CODE REVIEW

**Comment by ibauersachs** [comment]
I've previously used japicmp-maven-plugin in jitsi/ice4j and rejected clirr-maven-plugin, but can't remember why atm. But it seems weird that you don't need to specify a baseline version. What does clirr use?

**Comment by kingle** [comment]
japicmp-maven-plugin looks better.  I'll switch to use it -- according to their site, clirr is basically dead: https://siom79.github.io/japicmp/

**Comment by kingle** [comment]
Switched it with japicmp -- let me know if you prefer other parameter config: https://siom79.github.io/japicmp/MavenPlugin.html

**Comment by kingle** [comment]
baseline (old version) is latest released version if not specified.

**Comment by ibauersachs** [comment]
Let's see how this works out.

**Pull request merged**
