### PR TITLE
Fix restoring active position on byte buffers

### PR DESCRIPTION
**Pull request by ryru**
Wrong restored position lead to incomplete EDNS0 options parsing.

### CODE REVIEW

**Review by nresare — APPROVED** [review]
Thank you for the fix, and thank you for adding the tests.

**Comment by nresare** [comment]
Would you mind reformatting the tests with `mvn com.coveo:fmt-maven-plugin:format`? In this case the output turns out significantly worse looking than what you wrote, but I think it is a small price to pay to not spend a lot of time discussing formatting differences etc.

**Comment by ryru** [comment]
Patch is now formatted according `mvn com.coveo:fmt-maven-plugin:format`. What about the time out issue `NioTcpClientTest.testResponseStream:79 timed out waiting for messages` in CI?

**Comment by nresare** [comment]
I don't know what is happening with the failing tests. Tests run successfully locally here (macOS 11, Java 11) Maybe @ibauersachs knows?

**Comment by ibauersachs** [comment]
I don't know why they failed, rerun was successful, so I assume some spurious event on a GHA runner.

**Pull request merged**
