### PR TITLE
Master issue295 tsig fix

### PR DESCRIPTION
**Pull request by frankarinnet**
This pull request is in reference to: https://github.com/dnsjava/dnsjava/issues/295

There are still some TODOs, however, because I need some guidance on how to deal with thread safety in the TSIG.

So, don't merge this without commenting.

### CODE REVIEW

**Comment by frankarinnet** [comment]
Fixing the remaining code formatting issues makes it a bit harder to see what I've changed vs the original.
I'll make sure to fix them up before a final commit.

**Comment by ibauersachs** [comment]
Thank you! I'll need some time to work on this.

Could you in the meantime please help me out to make this easier:
- target the 3.5.x branch
- create a unit test that fails without your changes

If that's too complicated, then some sample code and zone file with keys pasted or attached here would also help a lot.

**Comment by frankarinnet** [comment]
I'll give the unit test a shot on Tuesday; these sorts of gory-DNS details are a little outside my experience, though.  My current testing has been against an NSD server in our staging environment.

**Comment by frankarinnet** [comment]
I've created:  https://github.com/frankarinnet/axfr

Which might be helpful for testing this.  It was the simplest program I could write to demonstrate this bug for manual testing.

But you will still need to:
* set up a DNS server
* with TSIG
* that allows full zone transfers (AXFR)
* configured with a few different-sized zones

I've been using:
* a small zone (with 8 lines)
* a medium zone (with 8k lines)
* a large zone (with 160k lines)

**Comment by ibauersachs** [comment]
Great, thank you!

**Comment by frankarinnet** [comment]
Since my fix branched from master, I may need to create a third PR properly branched from 3.5.x.

**Comment by frankarinnet** [comment]
Created https://github.com/dnsjava/dnsjava/pull/298, properly pointed against 3.5.x.

Any objections to me closing this PR?

**Comment by frankarinnet** [comment]
Closing.

**Pull request closed without merging**
